version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: admin
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: enviametest

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3307:3307
    restart: unless-stopped
    volumes:
      - ./db/enviametest.sql:/docker-entrypoint-initdb.d/enviametest.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  apinode:
    build:
      context: .
    container_name: node_container
    depends_on:
      - mysql-db

    ports:
      - 8000:8000
    volumes:
      - ./www/
    links:
      - mysql-db
    command: node dist/app.js
